# Generated by Django 2.2 on 2021-05-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='1', max_length=20, unique=True, verbose_name='MobileVersion')),
                ('web', models.CharField(default='1', max_length=20, unique=True, verbose_name='WebVersion')),
            ],
        ),
    ]
